# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "wordforms"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.3"
substring = "1.4.5"
unicode-segmentation = "1.12.0"

[profile.release]
opt-level=3
#debug = true
